apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: myfirstapp-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myfirstapp
    spec:
      containers:
      - name: myfirstapp
        image: martinpeck/myfirstapp:$BUILD_NUMBER
        ports:
        - containerPort: 80